# Generated by Django 4.2.5 on 2023-09-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPreprocessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('data_cleaning', models.BooleanField(default=False)),
                ('resize_width', models.IntegerField(default=0)),
                ('resize_height', models.IntegerField(default=0)),
                ('augmentation_rotation', models.BooleanField(default=False)),
                ('norm_standardization', models.CharField(default='none', max_length=15)),
                ('oversampling', models.BooleanField(default=False)),
                ('undersampling', models.BooleanField(default=False)),
                ('train_ratio', models.IntegerField(default=70)),
                ('val_ratio', models.IntegerField(default=15)),
                ('test_ratio', models.IntegerField(default=15)),
                ('shuffle_data', models.BooleanField(default=False)),
                ('extract_cnn_features', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PolypDetectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('architecture', models.CharField(max_length=50)),
                ('num_conv_layers', models.IntegerField(default=3)),
                ('kernel_size', models.CharField(default='3x3', max_length=5)),
                ('pooling_type', models.CharField(default='max', max_length=10)),
                ('pooling_size', models.CharField(default='2x2', max_length=5)),
                ('learning_rate', models.FloatField(default=0.001)),
                ('data_augmentation', models.BooleanField(default=False)),
                ('transfer_learning', models.BooleanField(default=False)),
                ('normalization', models.BooleanField(default=False)),
                ('input_image_size', models.CharField(default='128x128', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epochs', models.IntegerField()),
            ],
        ),
    ]
