# Generated by Django 4.2.5 on 2023-09-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_datapreprocessing_polypdetectionmodel_training'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPreprocessing',
        ),
        migrations.DeleteModel(
            name='PolypDetectionModel',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='citation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paper',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.TextField(blank=True, null=True),
        ),
    ]
