# Generated by Django 4.2.5 on 2023-09-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_docprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docprofile',
            name='licensenumber',
        ),
    ]
