# Generated by Django 4.2.5 on 2023-09-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_docprofile_add1_docprofile_add2_docprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docprofile',
            name='dob',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
