# Generated by Django 4.2.5 on 2023-09-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_alter_certification_doctor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='university',
        ),
    ]
