# Generated by Django 4.2.5 on 2023-10-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_medicalrecord_userprofile_country_userprofile_fname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('cancer_stage', models.CharField(blank=True, max_length=255)),
                ('biopsy_results', models.TextField(blank=True)),
                ('oncologist_name', models.CharField(blank=True, max_length=255)),
                ('allergy_name', models.CharField(blank=True, max_length=255)),
                ('allergy_severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10)),
                ('medication_name', models.CharField(blank=True, max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=255)),
                ('frequency', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
