# Generated by Django 4.2.5 on 2023-10-02 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_patientinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor.userprofile'),
        ),
    ]
