# Generated by Django 4.2.5 on 2023-10-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_remove_patientinfo_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
