# Generated by Django 4.2.5 on 2023-10-04 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0022_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.userprofile'),
        ),
    ]
