# Generated by Django 4.2.5 on 2023-10-04 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0023_patientinfo_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinfo',
            name='patient',
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
