# Generated by Django 4.2.5 on 2023-10-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0025_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='doctor_name',
            new_name='name',
        ),
    ]
