# Generated by Django 4.2.5 on 2023-10-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0026_rename_doctor_name_timeslot_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='name',
            new_name='doctor_name',
        ),
    ]
