# Generated by Django 4.2.5 on 2023-10-06 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0027_rename_name_timeslot_doctor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
