# Generated by Django 4.2.5 on 2023-10-06 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0028_remove_timeslot_doctor_name_timeslot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.docprofile'),
        ),
    ]
