# Generated by Django 4.2.5 on 2023-10-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0036_alter_appointment_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='app_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='app_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
