# Generated by Django 4.2.5 on 2023-10-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0039_docprofile_booked_time_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docprofile',
            name='booked_time_slots',
        ),
        migrations.AddField(
            model_name='docprofile',
            name='reset_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
