# Generated by Django 4.2.5 on 2024-02-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0050_docprofile_about_docprofile_college_docprofile_cyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
