# Generated by Django 4.2.5 on 2024-02-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0053_referpatient_referring_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='referpatient',
            name='case_sheet',
            field=models.FileField(blank=True, null=True, upload_to='case_sheets/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='referpatient',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referpatient',
            name='referring_doctor_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referpatient',
            name='referring_doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referpatient',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referpatient',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referpatient',
            name='referred_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
