# Generated by Django 4.2.5 on 2024-02-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0054_referpatient_case_sheet_referpatient_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referpatient',
            name='case_sheet',
            field=models.FileField(upload_to='case_sheets/%Y/%m/%d/'),
        ),
    ]
