# Generated by Django 4.2.5 on 2024-02-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0055_alter_referpatient_case_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referpatient',
            name='case_sheet',
            field=models.FileField(blank=True, null=True, upload_to='case_sheets/%Y/%m/%d/'),
        ),
    ]
