# Generated by Django 4.2.5 on 2024-02-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0057_referpatient_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='referpatient',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
