# Generated by Django 4.2.5 on 2024-02-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0058_referpatient_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referpatient',
            name='is_new',
        ),
    ]
