# Generated by Django 4.2.5 on 2024-03-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0067_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docprofile',
            name='hospital_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
