# Generated by Django 4.2.5 on 2024-03-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0068_alter_docprofile_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docprofile',
            name='college',
            field=models.TextField(blank=True, null=True),
        ),
    ]
