# Generated by Django 4.2.5 on 2024-03-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0069_alter_docprofile_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='docprofile',
            name='award',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docprofile',
            name='ayear',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
