# Generated by Django 4.2.5 on 2024-03-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0070_docprofile_award_docprofile_ayear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinfo',
            old_name='allergy_name',
            new_name='allergies',
        ),
        migrations.RenameField(
            model_name='patientinfo',
            old_name='start_date',
            new_name='colonoscopy_date',
        ),
        migrations.RenameField(
            model_name='patientinfo',
            old_name='dosage',
            new_name='colonoscopy_findings',
        ),
        migrations.RenameField(
            model_name='patientinfo',
            old_name='frequency',
            new_name='complications',
        ),
        migrations.RenameField(
            model_name='patientinfo',
            old_name='medication_name',
            new_name='presenting_symptoms',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='num_days',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='allergy_severity',
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='ct_scan_results',
            field=models.FileField(blank=True, upload_to='ct_scan_results/'),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='date_of_initiation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='response_to_treatment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='treatment_plan',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='biopsy_results',
            field=models.FileField(blank=True, upload_to='biopsy_results/'),
        ),
    ]
