# Generated by Django 4.2.5 on 2024-03-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0071_rename_allergy_name_patientinfo_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinfo',
            name='cancer_stage',
        ),
    ]
