# Generated by Django 4.2.5 on 2024-03-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0072_remove_patientinfo_cancer_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage_strength', models.CharField(max_length=50)),
                ('dosage_form', models.CharField(max_length=50)),
                ('route_of_admin', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('special_instructions', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='oncologist_name',
        ),
    ]
